mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('parse_mail.urls'))
]

mysite/parse_mail/urls.py
from django.contrib import admin
from django.urls import path

app_name = 'mail'
from .views import index, run_parse

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('parse/', run_parse, name='run_parse')
]

mysite/parse_mail/models.py
from django.db import models


# Create your models here.
class BaseMail(models.Model):
    email = models.CharField(max_length=64, verbose_name='email', unique=True)
    name = models.CharField(max_length=128, verbose_name='Имена в почте')
    email_in_body = models.CharField(max_length=255, verbose_name='Почтовые имена в теле письма')
    phones = models.CharField(max_length=255, verbose_name='Телефоны в письме')

    def __str__(self):
        return self.email

mysite/parse_mail/views.py
from django.shortcuts import render

from .mail import Mail
from .models import BaseMail


# Create your views here.
def index(request):
    return render(request, 'parse_mail/index.html')


def run_parse(request):
    a = Mail()
    a.run()

mysite/parse_mail/templates/parse_mail/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <h1>Парсинг почты</h1>
<div class="container">
  <form action = "{% url 'mail:run_parse' %}" method = 'post'>
{% csrf_token %}
{{ form.as_p }}
<button type="submit" class="btn btn-primary">Начать</button>
</form>



</div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>сканирование почты </h1>


<form action="/go" method="get">
    <button type="submit">Начать</button>
</form>
</body>